name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 12.8
      uses: actions/setup-node@v3
      with:
        node-version: 12.8
    - name: Install dependencies
      run: npm install
    - name: Test
      run: |
        npm test -- --configuration=ci
